name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install @azure/ai-text-analytics
          npm install cors --save
          npm install react-scripts --save

      - name: List installed packages (debugging)
        run: |
          echo "Listing installed packages:"
          npm list cors

      - name: Build and test
        run: |
          echo "Running build process..."
          npm run build --if-present || exit 1
          echo "Build completed."

      - name: Verify build directory
        run: |
          echo "Listing contents of the build directory:"
          ls -R ./build || echo "Build directory not found!"

      - name: Create ZIP file of build directory
        run: |
          zip -r build.zip ./build

      - name: Upload ZIP artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download ZIP artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip the build artifact
        run: |
          unzip build.zip -d build

      - name: Verify unzipped directory
        run: |
          echo "Listing contents of the unzipped build directory:"
          ls -R build || echo "Unzipped build directory not found!"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tikupload'
          slot-name: 'Production'
          package: ./build
